CREATE DATABASE customer_behavior;

-- IMP KPI’S (Total revenue, Total Customers, Average Review Rating, Repeat Purchase Rate)
SELECT 
    SUM(purchase_amount) AS total_revenue,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(review_rating), 2) AS avg_review_rating,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases
FROM
    customer;

-- Q1. Category-wise total sales?
SELECT 
    category, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY category
ORDER BY revenue DESC;

-- Q2. Revenue by season?
SELECT 
    season, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY season
ORDER BY revenue DESC;

-- Q3. Subscription vs non-subscription revenue?
SELECT 
    subscription_status, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY subscription_status;

-- Q4. Impact of discounts on sales?
SELECT 
    discount_applied, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY discount_applied;

-- Q5. Most used payment method?
SELECT 
    payment_method, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY payment_method
ORDER BY revenue DESC;

-- Q6. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender;

-- Q7. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);
    
-- Q8. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q9. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q10. Do subscribed customers spend more? Compare average spend and total revenue
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue DESC , avg_spend DESC;

-- Q11. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100 / COUNT(*), 2) AS discount_percentage
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q12. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
--      and show the count of each segment. 
SELECT 
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS Customer_segmentation ,
    COUNT(customer_id) AS total_customer
FROM
    customer
GROUP BY Customer_segmentation
ORDER BY total_customer;

-- Q13. What are the top 3 most purchased products within each category?
WITH item_counts AS (
		SELECT 
			category , 
			item_purchased , 
			count(customer_id) AS total_oders, 
			ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) AS item_rank
		FROM 
			customer 
		GROUP BY 
			category , item_purchased 
)
SELECT item_rank, category, item_purchased, total_oders
FROM item_counts
WHERE item_rank <= 3;

-- Q14. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q15. What is the revenue contribution of each age group?
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue DESC;
